name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn
      - run: yarn run lint --if-present
      - run: yarn test
      - run: yarn run build --if-present
        env:
          CI: true
